dist: trusty
sudo: required
before_install:
- "sudo apt-get update && sudo apt-get install --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended dvipng latex-xcolor"
script:
- mkdir _build
- pdflatex -halt-on-error -output-directory _build my-favorite-physicist.tex
notifications:
  email:
    recipients:
      - ahelm@ipfn.tecnico.ulisboa.pt
    on_success: change
    on_failure: always
    on_start:   never
